#!/usr/bin/env python
from littlechef_rackspace.runner import Runner, MissingRequiredArguments, InvalidConfiguration, InvalidCommand, parser
import sys

if __name__ == "__main__":
    r = Runner()
    try:
        r.main(sys.argv[1:])
    except MissingRequiredArguments:
        print "Not all arguments for command provided"
        parser.print_help()
    except InvalidConfiguration as e:
        print e.message
        parser.print_help()
    except InvalidCommand:
        print "Invalid command specified"
        parser.print_help()
